services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '0.0.0.0:1883:1883'
      - '0.0.0.0:9001:9001'
    volumes:
      - ./mosquitto:/etc/mosquitto:rw
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/passwd
      - ./mosquitto/data:/mosquitto/data:rw

  node-red:
    image: nodered/node-red:latest
    hostname: node-red
    container_name: node-red
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
    ports:
      - '0.0.0.0:1880:1880'
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:
